version: '3'
services:
  instance1:
    image: asset_service
    ports: 
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - ./serviceConfig.json:/app/serviceConfig.json

  instance2:
    image: asset_service
    ports: 
      - "8081:8080"
    environment:
      - PORT=8081
    volumes:
      - ./serviceConfig.json:/app/serviceConfig.json

  # instance3:
  #   image: asset_service
  #   ports: 
  #     - "8082:8080"
  #   environment:
  #     - PORT=8082
  #   volumes:
  #     - ./serverConfig.json:/app/serverConfig.json
  
  # instance4:
  #   image: asset_service
  #   ports: 
  #     - "8000:8080"
  #   environment:
  #     - PORT=8000
  #   volumes:
  #     - ./serverConfig.json:/app/serverConfig.json
  
  