// Code generated by Kitex v0.5.2. DO NOT EDIT.

package registryproxy

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	registry_proxy_service "registry_proxy/kitex_gen/registry_proxy_service"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ConnectServer(ctx context.Context, req *registry_proxy_service.ConnectRequest, callOptions ...callopt.Option) (r *registry_proxy_service.ConnectResponse, err error)
	HealthCheckServer(ctx context.Context, req *registry_proxy_service.HealtRequest, callOptions ...callopt.Option) (r *registry_proxy_service.HealthResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kRegistryProxyClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRegistryProxyClient struct {
	*kClient
}

func (p *kRegistryProxyClient) ConnectServer(ctx context.Context, req *registry_proxy_service.ConnectRequest, callOptions ...callopt.Option) (r *registry_proxy_service.ConnectResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ConnectServer(ctx, req)
}

func (p *kRegistryProxyClient) HealthCheckServer(ctx context.Context, req *registry_proxy_service.HealtRequest, callOptions ...callopt.Option) (r *registry_proxy_service.HealthResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.HealthCheckServer(ctx, req)
}
