// Code generated by Kitex v0.6.1. DO NOT EDIT.

package registryproxy

import (
	server "github.com/cloudwego/kitex/server"
	registry_proxy_service "registry_proxy/kitex_gen/registry_proxy_service"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler registry_proxy_service.RegistryProxy, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
