// Code generated by hertz generator.

package apigateway

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hertzgatewayMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _processgetrequestMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _processpostrequestMw() []app.HandlerFunc {
	// your code...
	return nil
}
