// Code generated by hertz generator.

package asset_api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	asset_api "hertz-server/biz/model/asset_api"
)

// QueryAsset .
// @router asset/query [GET]
func QueryAsset(ctx context.Context, c *app.RequestContext) {
	var err error
	var req asset_api.QueryAssetRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(asset_api.QueryAssetResponse)

	c.JSON(consts.StatusOK, resp)
}

// InsertAsset .
// @router asset/insert [POST]
func InsertAsset(ctx context.Context, c *app.RequestContext) {
	var err error
	var req asset_api.InsertAssetRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(asset_api.InsertAssetResponse)

	c.JSON(consts.StatusOK, resp)
}
