// Code generated by hertz generator.

package gateway

import (
	"context"

	gateway "hertzserver/biz/model/gateway"

	"github.com/cloudwego/hertz/pkg/app"
)

// HelloMethod .
// @router /hello [GET]
func HelloMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req gateway.HelloReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(gateway.HelloResp)

	// You can modify the logic of the entire function, not just the current template
	resp.RespBody = "hello," + req.Name // added logic

	c.JSON(200, resp)
}
