// Code generated by hertz generator.

package handler

import (
	"context"
	"fmt"
	"log"

	repository "api-gateway/hertz_server/biz/model/repository"

	"github.com/cloudwego/hertz/pkg/app"
)

// Ping .
func InsertDataInMongo(ctx context.Context, c *app.RequestContext) {
	// Call the function to test the MongoDB connection and data insertion
	err := repository.InsertTestData()
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("Data inserted successfully!")
}
