// Code generated by Kitex v0.6.0. DO NOT EDIT.

package calculatorservice

import (
	calculator "rpc_services/calculatorService/kitex_gen/calculator"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AddNums(ctx context.Context, request *calculator.CalculationRequest, callOptions ...callopt.Option) (r *calculator.CalculationResponse, err error)
	SubNums(ctx context.Context, request *calculator.CalculationRequest, callOptions ...callopt.Option) (r *calculator.CalculationResponse, err error)
	DivNums(ctx context.Context, request *calculator.CalculationRequest, callOptions ...callopt.Option) (r *calculator.CalculationResponse, err error)
	MultiplyNums(ctx context.Context, request *calculator.CalculationRequest, callOptions ...callopt.Option) (r *calculator.CalculationResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCalculatorServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCalculatorServiceClient struct {
	*kClient
}

func (p *kCalculatorServiceClient) AddNums(ctx context.Context, request *calculator.CalculationRequest, callOptions ...callopt.Option) (r *calculator.CalculationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddNums(ctx, request)
}

func (p *kCalculatorServiceClient) SubNums(ctx context.Context, request *calculator.CalculationRequest, callOptions ...callopt.Option) (r *calculator.CalculationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SubNums(ctx, request)
}

func (p *kCalculatorServiceClient) DivNums(ctx context.Context, request *calculator.CalculationRequest, callOptions ...callopt.Option) (r *calculator.CalculationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DivNums(ctx, request)
}

func (p *kCalculatorServiceClient) MultiplyNums(ctx context.Context, request *calculator.CalculationRequest, callOptions ...callopt.Option) (r *calculator.CalculationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MultiplyNums(ctx, request)
}
