version: '3'
services:
  apigateway:
    network_mode: host
    image: api-gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: hertzgateway
    # deploy:
    #   replicas: 1