// Code generated by hertz generator.

package main

import (
	handler "api-gateway/hertz_server/biz/handler"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
	r.POST("/register", handler.Register)
	r.GET("/show", handler.DisplayAll)
}
