// Code generated by hertz generator.

package main

import (
	handler "api-gateway/hertz_server/biz/handler"

	servicehandler "api-gateway/hertz_server/biz/handler/servicehandler"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {

	// Route for ping (HealthCheck of Hertz Server)
	r.GET("/ping", handler.Ping)

	// Route for admin registration
	r.POST("/register", servicehandler.Register)

	// Route for admin info updates
	r.PUT("/update", servicehandler.Update)

	// Route to connect servers
	r.POST("/connect", servicehandler.Connect)

	// Route for healthchecks
	r.POST("/health", servicehandler.HealthCheck)
}
